name: Update Src List
on:
  push
jobs:
  updateMakeList:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repo
      - shell: bash
        run: ls -Rpm1 img/src/ > src.txt
        
      - name: Save changes
        uses: actions-go/push@v1 # pushing the changes to the repo
        with:
          force: true
          commit-files: src.txt
          commit-message: Updating make list
